const sequelize = require("./config/db");
const { Product } = require("./models");

const market = [
{title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849230/minc/donCareJacket_srmt3o.png",
    price: 100,
  },
    {title: `MKI MIYUKI ZOKU AW20 Down jacket`,
    size: "Large",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849236/minc/MMZjacket_wkm3qj.png",
    price: 50,
  },
  {title: `BLOOD ORANGE "The Field" t-shirt`,
    size: "Large",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849230/minc/fieldTop_isruk7.png",
    price: 45,
  },
    {title: `WOMENS ACCESSORIES COLLECTION`,
    size: "Raffle Tickets",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849235/minc/raffle_lzc2po.png",
    price: 2,
  },
    {title: `VAN-DAL Vintage Purse`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849229/minc/vanDal_k1qhmm.png",
    price: 40,
  },
    {title: `VINTAGE PURSE`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849235/minc/vinPurse1_wdrjbh.png",
    price: 35,
  },
    {title: `VINTAGE PURSE`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849234/minc/vinPurse2_ilx9qq.png",
    price: 25,
  },
    {title: `VINTAGE EARRINGS`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849234/minc/earrings1_pmkiwj.png",
    price: 30,
  },
    {title: `Vintage Pot"`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849235/minc/pot_whmjwm.png",
    price: 25,
  },
    {title: `VINTAGE BLOUSE`,
    size: "Medium",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849232/minc/vinBlouse1_gxk4au.png",
    price: 50,
  },
    {title: `VINTAGE TOP`,
    size: "Medium",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849232/minc/vinTop1_yozwdh.png",
    price: 50,
  },
    {title: `VINTAGE SKIRT`,
    size: "Small",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849232/minc/vinSkirt1_itehni.png",
    price: 50,
  },
    {title: `VINTAGE TOP`,
    size: "Medium",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849233/minc/vinTop2_izktxg.png",
    price: 60,
  },
    {title: `VINTAGE SUEDE SKIRT`,
    size: "S - M",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849230/minc/vinSkirt2_o9xnpo.png",
    price: 75,
  },
    {title: `VINTAGE SKIRT`,
    size: "XLarge",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849230/minc/vinSkirt3_jg0bbb.png",
    price: 30,
  },
  {title: `VINTAGE Cardigan`,
    size: "Medium",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849230/minc/vinCardi_utkod5.png",
    price: 40,
  },
  {title: `VINTAGE Neckless`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849229/minc/vinNeck1_bzqdmf.png",
    price: 50,
  },
    {title: `VINTAGE Neckless`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849227/minc/vinNeck2_kgzynb.png",
    price: 50,
  },
  {title: `VINTAGE Earrings`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849227/minc/earring2_gcztum.png",
    price: 30,
  },
  {title: `VINTAGE Neckless`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849227/minc/vinNeck3_xi90ub.png",
    price: 40,
  },
  {title: `VINTAGE Neckless`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849227/minc/vinNeck4_tmimeb.png",
    price: 35,
  },
  {title: `VINTAGE Neckless`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849228/minc/vinNeck5_hys5q2.png",
    price: 40,
  },
  {title: `ILilily Cadet Hat`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849227/minc/cadetHat_xrfxru.png",
    price: 80,
  }
];

(async () => {
  try {
    await sequelize.authenticate();
    console.log("DB conectada");

    await Product.bulkCreate(market);
    console.log("Productos insertados correctamente");

    process.exit();
  } catch (error) {
    console.error("Error al insertar productos:", error);
    process.exit(1);
  }
})();
